name = "cositeca-telegram-bot"
main = "worker.js"
compatibility_date = "2026-09-01"

[observability]
enabled = false

[[kv_namespaces]]
binding = "BOT_KV"
id = "dd15d41ca6be4acbb285c17e41ff784e"

[[services]]
binding = "TMDB_PROXY"
service = "cositeca-tmdb-proxy"
